//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc.BookManagement.Resources.SharedResources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource_tr {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource_tr() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Mvc.BookManagement.Resources.SharedResources.SharedResource_tr", typeof(SharedResource_tr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string BookCatalog {
            get {
                return ResourceManager.GetString("BookCatalog", resourceCulture);
            }
        }
        
        internal static string AddNewBook {
            get {
                return ResourceManager.GetString("AddNewBook", resourceCulture);
            }
        }
        
        internal static string NoBooksInCatalog {
            get {
                return ResourceManager.GetString("NoBooksInCatalog", resourceCulture);
            }
        }
        
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        internal static string Genre {
            get {
                return ResourceManager.GetString("Genre", resourceCulture);
            }
        }
        
        internal static string PageCount {
            get {
                return ResourceManager.GetString("PageCount", resourceCulture);
            }
        }
        
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        internal static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        internal static string SaveBook {
            get {
                return ResourceManager.GetString("SaveBook", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        internal static string AddNewBookTitle {
            get {
                return ResourceManager.GetString("AddNewBookTitle", resourceCulture);
            }
        }
        
        internal static string EditBookTitle {
            get {
                return ResourceManager.GetString("EditBookTitle", resourceCulture);
            }
        }
        
        internal static string BookDetailsTitle {
            get {
                return ResourceManager.GetString("BookDetailsTitle", resourceCulture);
            }
        }
        
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        internal static string BookCreatedSuccess {
            get {
                return ResourceManager.GetString("BookCreatedSuccess", resourceCulture);
            }
        }
        
        internal static string BookUpdatedSuccess {
            get {
                return ResourceManager.GetString("BookUpdatedSuccess", resourceCulture);
            }
        }
        
        internal static string BookDeletedSuccess {
            get {
                return ResourceManager.GetString("BookDeletedSuccess", resourceCulture);
            }
        }
        
        internal static string DeleteError {
            get {
                return ResourceManager.GetString("DeleteError", resourceCulture);
            }
        }
        
        internal static string ValidationError {
            get {
                return ResourceManager.GetString("ValidationError", resourceCulture);
            }
        }
        
        internal static string GeneralError {
            get {
                return ResourceManager.GetString("GeneralError", resourceCulture);
            }
        }
        
        internal static string IsRequired {
            get {
                return ResourceManager.GetString("IsRequired", resourceCulture);
            }
        }
        
        internal static string PageCountRange {
            get {
                return ResourceManager.GetString("PageCountRange", resourceCulture);
            }
        }
        
        internal static string DeleteConfirmationMessage {
            get {
                return ResourceManager.GetString("DeleteConfirmationMessage", resourceCulture);
            }
        }
        
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        internal static string Turkish {
            get {
                return ResourceManager.GetString("Turkish", resourceCulture);
            }
        }
        
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        internal static string TitleMaxLength {
            get {
                return ResourceManager.GetString("TitleMaxLength", resourceCulture);
            }
        }
        
        internal static string AuthorMaxLength {
            get {
                return ResourceManager.GetString("AuthorMaxLength", resourceCulture);
            }
        }
        
        internal static string GenreMaxLength {
            get {
                return ResourceManager.GetString("GenreMaxLength", resourceCulture);
            }
        }
        
        internal static string PageCountMin {
            get {
                return ResourceManager.GetString("PageCountMin", resourceCulture);
            }
        }
        
        internal static string PageCountMax {
            get {
                return ResourceManager.GetString("PageCountMax", resourceCulture);
            }
        }
    }
}
